version: "3"

services:
  # Dev DB
  database-dev:
    image: postgres
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=abcd#1234"
      - "POSTGRES_DB=dev"
    ports:
      - "5432:5432"
    restart: always

  # Dev DB
  database-test:
    image: postgres
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=abcd#1234"
      - "POSTGRES_DB=test"
    ports:
      - "5433:5432"
    restart: always
